version: '3.8'

services:
  jira-app:
    image: jira-rush-app
    container_name: jira-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/jira
    env_file:
      - jira.env
    networks:
      - jira-network
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jira-network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - jira-app
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/static:/usr/share/nginx/html/static:ro
    ports:
      - "80:80"
    networks:
      - jira-network

networks:
  jira-network:
    driver: bridge

volumes:
  postgres-data:
